# Generated by Django 5.1.6 on 2025-02-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('seeker', 'Home Seeker'), ('owner', 'Property Owner')], default='seeker', max_length=20),
        ),
    ]
